version: "3.8"

services:
  db:
    image: postgres:15
    container_name: trading-db
    working_dir: /database
    restart: unless-stopped
    environment:
      POSTGRES_DB: trading_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - trading-net

volumes:
  postgres_data:

networks:
  trading-net: