[tool.black]
line-length = 88
target-version = ['py313']

[tool.isort]
profile = "black"

[tool.mypy]
python_version = 3.13
strict = true
ignore_missing_imports = true

[tool.coverage.html]
directory = "coverage_html_report"
