"""uniq account api key

Revision ID: b06c12125b46
Revises: ed0e28ad03f5
Create Date: 2025-07-06 20:51:36.587414

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b06c12125b46"
down_revision: Union[str, Sequence[str], None] = "ed0e28ad03f5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "account_uniq", "trading_environments", ["account_api_id"]
    )
    stmt = "CREATE EXTENSION IF NOT EXISTS citext;"
    op.execute(stmt)
    op.alter_column(
        "users",
        "email",
        existing_type=sa.VARCHAR(length=256),
        type_=postgresql.CITEXT(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "email",
        existing_type=postgresql.CITEXT(),
        type_=sa.VARCHAR(length=256),
        existing_nullable=False,
    )
    op.drop_constraint("account_uniq", "trading_environments", type_="unique")
    # ### end Alembic commands ###
