"""delete api_secret in tables environments

Revision ID: ed0e28ad03f5
Revises: f15550e77ddb
Create Date: 2025-06-29 15:30:27.656080

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ed0e28ad03f5"
down_revision: Union[str, Sequence[str], None] = "f15550e77ddb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("trading_environments", "api_secret")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "trading_environments",
        sa.Column("api_secret", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
