"""add username and admin in  user

Revision ID: f15550e77ddb
Revises: b0f46904e767
Create Date: 2025-06-29 14:57:53.835885

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f15550e77ddb"
down_revision: Union[str, Sequence[str], None] = "b0f46904e767"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("username", sa.String(), nullable=False))
    op.add_column("users", sa.Column("admin", sa.Boolean(), nullable=False))
    op.create_unique_constraint("username_constraint", "users", ["username"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("username_constraint", "users", type_="unique")
    op.drop_column("users", "admin")
    op.drop_column("users", "username")
    # ### end Alembic commands ###
