@startuml
left to right direction
skinparam packageStyle rectangle

actor "Trader User" as TU
actor Admin as A

rectangle "Trading Robot System" {
  ' Управление учётными записями и средами
  (Регистрироваться)                  as REG
  (Логиниться)                                   as LOG
  (Создавать индивдуальное торговое пространство) as CTENV
  (Выбрать индивдуальное торговое пространство)   as STENV
  (Удалить индивдуальное торговое пространство)   as DTENV

  ' Настройка и управление стратегиями
  (Создавть стратегии)                       as DSG
  (Просматриавть список готовых стратегий)   as LSTSTR
  (Привязывать стратегии к окружению)        as AST

  ' Основные торговые сценарии (выполняются в рамках выбранной среды)
  (Управлять настройками)                 as CS
  (Запускать бота)                      as SE
  (Останавливать бота)                  as ST
  (Просмотр статуса подписок и бота)    as VS
  (Просмотр портфолио)                  as VP
  (Просмотр детальной информации по инструментам) as INSTR
  (Выставление ордеорв вручную)         as PMO
  (Просмотр логов и получение критических соощений) as RA

  ' Расширенный выбор инструментов/стратегий
  (Выбор инструмента)         as TIS
  (Выбор стратегии)           as STR
}

' Аутентификация и среды
TU --> REG
TU --> LOG
TU --> CTENV
TU --> STENV
TU --> DTENV

' Стратегии
TU --> DSG
TU --> LSTSTR
TU --> AST


' Торговля в рамках среды
TU --> CS
TU --> SE
TU --> ST
TU --> VS
TU --> VP
TU --> PMO
TU --> RA
TU --> TIS
TU --> STR
TU --> INSTR

' Админ остаётся за глобальным конфигом
A --> CS
A --> RA
@enduml